var args ="&idecko="+string(unique)+"&taken="+string(targetid)+"&round="+string(tah)
+"&x0="+string(a[0].x)+"&y0="+string(a[0].y)
+"&x1="+string(a[1].x)+"&y1="+string(a[1].y)
+"&x2="+string(a[2].x)+"&y2="+string(a[2].y)
+"&x3="+string(a[3].x)+"&y3="+string(a[3].y)
+"&x4="+string(a[4].x)+"&y4="+string(a[4].y)
+"&x5="+string(a[5].x)+"&y5="+string(a[5].y)
+"&x6="+string(a[6].x)+"&y6="+string(a[6].y)
+"&x7="+string(a[7].x)+"&y7="+string(a[7].y)
+"&x8="+string(a[8].x)+"&y8="+string(a[8].y)
+"&x9="+string(a[9].x)+"&y9="+string(a[9].y)
+"&x10="+string(b[0].x)+"&y10="+string(b[0].y)
+"&x11="+string(b[1].x)+"&y11="+string(b[1].y)
+"&x12="+string(b[2].x)+"&y12="+string(b[2].y)
+"&x13="+string(b[3].x)+"&y13="+string(b[3].y)
+"&x14="+string(b[4].x)+"&y14="+string(b[4].y)
+"&x15="+string(b[5].x)+"&y15="+string(b[5].y)
+"&x16="+string(b[6].x)+"&y16="+string(b[6].y)
+"&x17="+string(b[7].x)+"&y17="+string(b[7].y)
+"&x18="+string(b[8].x)+"&y18="+string(b[8].y)
+"&x19="+string(b[9].x)+"&y19="+string(b[9].y)
+"&hash=4234";
//show_message_async(args);
http_post_string("https://mafianje.chytrak.cz/fruitpool/gamepos.php", args);